version: '3'

services:
  web:
    image: movie-api
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production 
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  db:
    image: mongo:latest
    environment:
      - MONGODB_DATABASE="test"
    ports:
      - "27017:27017"